### ISSUE TITLE
Pingplugin and Proxifier not working

### ISSUE THREAD

**Issue by francismanjares** [karashiiro/PingPlugin#25]
Hi, I noticed Pingplugin shows 0ms and showing 127.0.0.1 while using proxifier, it was working before EW patch.

![image](https://user-images.githubusercontent.com/19704272/145603906-c1e88b0b-0289-4ed0-9044-a72515bf107c.png)

While turning off proxifier pingplugin works fine. I alreay reinstalled the plugin multiple times . not sure what to do for it to work :(

Thank you.

**Comment by karashiiro** [comment]
There is one hook that PingPlugin uses specifically to get around this, I'll fix it when I have a moment to deal with the queues.

**Comment by karashiiro** [comment]
Should be fixed with v1.14.2, let me know if it works.

**Comment by francismanjares** [comment]
tried it a while ago, it still show 127.0.0.1, tried deleting it manually from the plugin config to regenerate config but still the same. ;_;

**Comment by karashiiro** [comment]
v1.14.3 released, how about this? It worked for me when I tested it by disabling the normal ping trackers.

**Comment by francismanjares** [comment]
it is working now :) thank you <3
