### ISSUE TITLE
PingPlugin under WINE reports 0ms latency, causes high winedevice.exe load

### ISSUE THREAD

**Issue by belthesar** [karashiiro/PingPlugin#27]
OS: Pop!_OS 21.04 + WINE 6.21 GloriousEggroll

Howdy folks. I'm one of those crackpot Linux users out there. I've had pretty good success with PingPlugin prior to Endwalker, but since this patch, things have been real silly all over the place, and I've been tracing issues. Most recent one seems to surround PingPlugin. 

Since Endwalker, PingPlugin has been returning 0ms, which my assumption was that SE had disabled ICMP Echo to save any resources they could, and didn't think much of it. However, I've also had a lot of hitching and other issues recently related to sound, so I've been tracing quite a bit of weird performance issues, and it's been a bit of a mess to trace. After checking the active issues however, and seeing the other open issues, I'm lead to believe there's actually a defect there, and likely some sort of WINE nuance that will need to be accounted for to get things working okay again. 

I'm going to see if there's some additional debug info I can pull out for you to help with this, as I know as this issue stands there's not much to go off of, and the likelihood that you have a test environment to work with is low here. Regardless, LMK if there's anything targeted I can to to pull more data out for you. Thanks!

**Comment by karashiiro** [comment]
This is related to the same underlying problem as #24 and #25, there's a hook I haven't updated yet that handles all of the environments where normal pings don't work. I'll be fixing this today.

**Comment by belthesar** [comment]
Thanks! I have testing builds enabled, so I can confirm this fix addresses the issue once the test build is live.

**Comment by karashiiro** [comment]
Should be fixed with v1.14.2, let me know if it works.

**Comment by Rohtea** [comment]
Another Linux user here, unfortunately it still shows 0ms on v1.14.2

**Comment by karashiiro** [comment]
v1.14.3 released, how about this? It worked for me when I tested it by disabling the normal ping trackers.
